package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.CanteenDishCategory;
import org.linlinjava.litemall.db.domain.CanteenDishCategoryExample;

public interface CanteenDishCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    long countByExample(CanteenDishCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int deleteByExample(CanteenDishCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int insert(CanteenDishCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int insertSelective(CanteenDishCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    CanteenDishCategory selectOneByExample(CanteenDishCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    CanteenDishCategory selectOneByExampleSelective(@Param("example") CanteenDishCategoryExample example, @Param("selective") CanteenDishCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    List<CanteenDishCategory> selectByExampleSelective(@Param("example") CanteenDishCategoryExample example, @Param("selective") CanteenDishCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    List<CanteenDishCategory> selectByExample(CanteenDishCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    CanteenDishCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CanteenDishCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    CanteenDishCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    CanteenDishCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CanteenDishCategory record, @Param("example") CanteenDishCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CanteenDishCategory record, @Param("example") CanteenDishCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CanteenDishCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CanteenDishCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CanteenDishCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_dish_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}