package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.CanteenOrder;
import org.linlinjava.litemall.db.domain.CanteenOrderExample;

public interface CanteenOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    long countByExample(CanteenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int deleteByExample(CanteenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int insert(CanteenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int insertSelective(CanteenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    CanteenOrder selectOneByExample(CanteenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    CanteenOrder selectOneByExampleSelective(@Param("example") CanteenOrderExample example, @Param("selective") CanteenOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    List<CanteenOrder> selectByExampleSelective(@Param("example") CanteenOrderExample example, @Param("selective") CanteenOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    List<CanteenOrder> selectByExample(CanteenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    CanteenOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CanteenOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    CanteenOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    CanteenOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CanteenOrder record, @Param("example") CanteenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CanteenOrder record, @Param("example") CanteenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CanteenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CanteenOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") CanteenOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canteen_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}