package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallBcUser;
import org.linlinjava.litemall.db.domain.LitemallBcUserExample;

public interface LitemallBcUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    long countByExample(LitemallBcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallBcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int insert(LitemallBcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int insertSelective(LitemallBcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    LitemallBcUser selectOneByExample(LitemallBcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    LitemallBcUser selectOneByExampleSelective(@Param("example") LitemallBcUserExample example, @Param("selective") LitemallBcUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    List<LitemallBcUser> selectByExampleSelective(@Param("example") LitemallBcUserExample example, @Param("selective") LitemallBcUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    List<LitemallBcUser> selectByExample(LitemallBcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    LitemallBcUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallBcUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    LitemallBcUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    LitemallBcUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallBcUser record, @Param("example") LitemallBcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallBcUser record, @Param("example") LitemallBcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallBcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallBcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallBcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_bc_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}