package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMealOrder;
import org.linlinjava.litemall.db.domain.LitemallMealOrderExample;

public interface LitemallMealOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallMealOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMealOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int insert(LitemallMealOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMealOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    LitemallMealOrder selectOneByExample(LitemallMealOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    LitemallMealOrder selectOneByExampleSelective(@Param("example") LitemallMealOrderExample example, @Param("selective") LitemallMealOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    List<LitemallMealOrder> selectByExampleSelective(@Param("example") LitemallMealOrderExample example, @Param("selective") LitemallMealOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    List<LitemallMealOrder> selectByExample(LitemallMealOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    LitemallMealOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallMealOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    LitemallMealOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    LitemallMealOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMealOrder record, @Param("example") LitemallMealOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMealOrder record, @Param("example") LitemallMealOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMealOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMealOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallMealOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_meal_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}