package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallDailyMenu;
import org.linlinjava.litemall.db.domain.LitemallDailyMenuExample;

public interface LitemallDailyMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    long countByExample(LitemallDailyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallDailyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int insert(LitemallDailyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int insertSelective(LitemallDailyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    LitemallDailyMenu selectOneByExample(LitemallDailyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    LitemallDailyMenu selectOneByExampleSelective(@Param("example") LitemallDailyMenuExample example, @Param("selective") LitemallDailyMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    List<LitemallDailyMenu> selectByExampleSelective(@Param("example") LitemallDailyMenuExample example, @Param("selective") LitemallDailyMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    List<LitemallDailyMenu> selectByExample(LitemallDailyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    LitemallDailyMenu selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallDailyMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    LitemallDailyMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    LitemallDailyMenu selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallDailyMenu record, @Param("example") LitemallDailyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallDailyMenu record, @Param("example") LitemallDailyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallDailyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallDailyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallDailyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}