package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTiming;
import org.linlinjava.litemall.db.domain.LitemallTimingExample;

public interface LitemallTimingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    long countByExample(LitemallTimingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTimingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    int insert(LitemallTiming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTiming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    LitemallTiming selectOneByExample(LitemallTimingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    LitemallTiming selectOneByExampleSelective(@Param("example") LitemallTimingExample example, @Param("selective") LitemallTiming.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    List<LitemallTiming> selectByExampleSelective(@Param("example") LitemallTimingExample example, @Param("selective") LitemallTiming.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    List<LitemallTiming> selectByExample(LitemallTimingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    LitemallTiming selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTiming.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    LitemallTiming selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTiming record, @Param("example") LitemallTimingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTiming record, @Param("example") LitemallTimingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTiming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_timing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTiming record);
}