package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallDishes;
import org.linlinjava.litemall.db.domain.LitemallDishesExample;

public interface LitemallDishesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    long countByExample(LitemallDishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallDishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int insert(LitemallDishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int insertSelective(LitemallDishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    LitemallDishes selectOneByExample(LitemallDishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    LitemallDishes selectOneByExampleSelective(@Param("example") LitemallDishesExample example, @Param("selective") LitemallDishes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    List<LitemallDishes> selectByExampleSelective(@Param("example") LitemallDishesExample example, @Param("selective") LitemallDishes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    List<LitemallDishes> selectByExample(LitemallDishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    LitemallDishes selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallDishes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    LitemallDishes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    LitemallDishes selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallDishes record, @Param("example") LitemallDishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallDishes record, @Param("example") LitemallDishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallDishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallDishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallDishesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_dishes
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}