package org.linlinjava.litemall.db.domain;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class LitemallDailyMenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public LitemallDailyMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public LitemallDailyMenuExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public LitemallDailyMenuExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        LitemallDailyMenuExample example = new LitemallDailyMenuExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public LitemallDailyMenuExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public LitemallDailyMenuExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("`date` is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("`date` is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(LocalDate value) {
            addCriterion("`date` =", value, "date");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDateEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("`date` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(LocalDate value) {
            addCriterion("`date` <>", value, "date");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDateNotEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("`date` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(LocalDate value) {
            addCriterion("`date` >", value, "date");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDateGreaterThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("`date` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(LocalDate value) {
            addCriterion("`date` >=", value, "date");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDateGreaterThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("`date` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDateLessThan(LocalDate value) {
            addCriterion("`date` <", value, "date");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDateLessThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("`date` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(LocalDate value) {
            addCriterion("`date` <=", value, "date");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDateLessThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("`date` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDateIn(List<LocalDate> values) {
            addCriterion("`date` in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<LocalDate> values) {
            addCriterion("`date` not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(LocalDate value1, LocalDate value2) {
            addCriterion("`date` between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("`date` not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andTimingIdIsNull() {
            addCriterion("timing_id is null");
            return (Criteria) this;
        }

        public Criteria andTimingIdIsNotNull() {
            addCriterion("timing_id is not null");
            return (Criteria) this;
        }

        public Criteria andTimingIdEqualTo(Integer value) {
            addCriterion("timing_id =", value, "timingId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingIdEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingIdNotEqualTo(Integer value) {
            addCriterion("timing_id <>", value, "timingId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingIdNotEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingIdGreaterThan(Integer value) {
            addCriterion("timing_id >", value, "timingId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingIdGreaterThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("timing_id >=", value, "timingId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingIdGreaterThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingIdLessThan(Integer value) {
            addCriterion("timing_id <", value, "timingId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingIdLessThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingIdLessThanOrEqualTo(Integer value) {
            addCriterion("timing_id <=", value, "timingId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingIdLessThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingIdIn(List<Integer> values) {
            addCriterion("timing_id in", values, "timingId");
            return (Criteria) this;
        }

        public Criteria andTimingIdNotIn(List<Integer> values) {
            addCriterion("timing_id not in", values, "timingId");
            return (Criteria) this;
        }

        public Criteria andTimingIdBetween(Integer value1, Integer value2) {
            addCriterion("timing_id between", value1, value2, "timingId");
            return (Criteria) this;
        }

        public Criteria andTimingIdNotBetween(Integer value1, Integer value2) {
            addCriterion("timing_id not between", value1, value2, "timingId");
            return (Criteria) this;
        }

        public Criteria andTimingNameIsNull() {
            addCriterion("timing_name is null");
            return (Criteria) this;
        }

        public Criteria andTimingNameIsNotNull() {
            addCriterion("timing_name is not null");
            return (Criteria) this;
        }

        public Criteria andTimingNameEqualTo(String value) {
            addCriterion("timing_name =", value, "timingName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingNameEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingNameNotEqualTo(String value) {
            addCriterion("timing_name <>", value, "timingName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingNameNotEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingNameGreaterThan(String value) {
            addCriterion("timing_name >", value, "timingName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingNameGreaterThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingNameGreaterThanOrEqualTo(String value) {
            addCriterion("timing_name >=", value, "timingName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingNameGreaterThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingNameLessThan(String value) {
            addCriterion("timing_name <", value, "timingName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingNameLessThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingNameLessThanOrEqualTo(String value) {
            addCriterion("timing_name <=", value, "timingName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andTimingNameLessThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("timing_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTimingNameLike(String value) {
            addCriterion("timing_name like", value, "timingName");
            return (Criteria) this;
        }

        public Criteria andTimingNameNotLike(String value) {
            addCriterion("timing_name not like", value, "timingName");
            return (Criteria) this;
        }

        public Criteria andTimingNameIn(List<String> values) {
            addCriterion("timing_name in", values, "timingName");
            return (Criteria) this;
        }

        public Criteria andTimingNameNotIn(List<String> values) {
            addCriterion("timing_name not in", values, "timingName");
            return (Criteria) this;
        }

        public Criteria andTimingNameBetween(String value1, String value2) {
            addCriterion("timing_name between", value1, value2, "timingName");
            return (Criteria) this;
        }

        public Criteria andTimingNameNotBetween(String value1, String value2) {
            addCriterion("timing_name not between", value1, value2, "timingName");
            return (Criteria) this;
        }

        public Criteria andDishesIdIsNull() {
            addCriterion("dishes_id is null");
            return (Criteria) this;
        }

        public Criteria andDishesIdIsNotNull() {
            addCriterion("dishes_id is not null");
            return (Criteria) this;
        }

        public Criteria andDishesIdEqualTo(Integer value) {
            addCriterion("dishes_id =", value, "dishesId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesIdEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesIdNotEqualTo(Integer value) {
            addCriterion("dishes_id <>", value, "dishesId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesIdNotEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesIdGreaterThan(Integer value) {
            addCriterion("dishes_id >", value, "dishesId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesIdGreaterThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dishes_id >=", value, "dishesId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesIdGreaterThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesIdLessThan(Integer value) {
            addCriterion("dishes_id <", value, "dishesId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesIdLessThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesIdLessThanOrEqualTo(Integer value) {
            addCriterion("dishes_id <=", value, "dishesId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesIdLessThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesIdIn(List<Integer> values) {
            addCriterion("dishes_id in", values, "dishesId");
            return (Criteria) this;
        }

        public Criteria andDishesIdNotIn(List<Integer> values) {
            addCriterion("dishes_id not in", values, "dishesId");
            return (Criteria) this;
        }

        public Criteria andDishesIdBetween(Integer value1, Integer value2) {
            addCriterion("dishes_id between", value1, value2, "dishesId");
            return (Criteria) this;
        }

        public Criteria andDishesIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dishes_id not between", value1, value2, "dishesId");
            return (Criteria) this;
        }

        public Criteria andDishesNameIsNull() {
            addCriterion("dishes_name is null");
            return (Criteria) this;
        }

        public Criteria andDishesNameIsNotNull() {
            addCriterion("dishes_name is not null");
            return (Criteria) this;
        }

        public Criteria andDishesNameEqualTo(String value) {
            addCriterion("dishes_name =", value, "dishesName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesNameEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesNameNotEqualTo(String value) {
            addCriterion("dishes_name <>", value, "dishesName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesNameNotEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesNameGreaterThan(String value) {
            addCriterion("dishes_name >", value, "dishesName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesNameGreaterThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesNameGreaterThanOrEqualTo(String value) {
            addCriterion("dishes_name >=", value, "dishesName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesNameGreaterThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesNameLessThan(String value) {
            addCriterion("dishes_name <", value, "dishesName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesNameLessThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesNameLessThanOrEqualTo(String value) {
            addCriterion("dishes_name <=", value, "dishesName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesNameLessThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesNameLike(String value) {
            addCriterion("dishes_name like", value, "dishesName");
            return (Criteria) this;
        }

        public Criteria andDishesNameNotLike(String value) {
            addCriterion("dishes_name not like", value, "dishesName");
            return (Criteria) this;
        }

        public Criteria andDishesNameIn(List<String> values) {
            addCriterion("dishes_name in", values, "dishesName");
            return (Criteria) this;
        }

        public Criteria andDishesNameNotIn(List<String> values) {
            addCriterion("dishes_name not in", values, "dishesName");
            return (Criteria) this;
        }

        public Criteria andDishesNameBetween(String value1, String value2) {
            addCriterion("dishes_name between", value1, value2, "dishesName");
            return (Criteria) this;
        }

        public Criteria andDishesNameNotBetween(String value1, String value2) {
            addCriterion("dishes_name not between", value1, value2, "dishesName");
            return (Criteria) this;
        }

        public Criteria andDishesBriefIsNull() {
            addCriterion("dishes_brief is null");
            return (Criteria) this;
        }

        public Criteria andDishesBriefIsNotNull() {
            addCriterion("dishes_brief is not null");
            return (Criteria) this;
        }

        public Criteria andDishesBriefEqualTo(String value) {
            addCriterion("dishes_brief =", value, "dishesBrief");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesBriefEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_brief = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesBriefNotEqualTo(String value) {
            addCriterion("dishes_brief <>", value, "dishesBrief");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesBriefNotEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_brief <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesBriefGreaterThan(String value) {
            addCriterion("dishes_brief >", value, "dishesBrief");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesBriefGreaterThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_brief > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesBriefGreaterThanOrEqualTo(String value) {
            addCriterion("dishes_brief >=", value, "dishesBrief");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesBriefGreaterThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_brief >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesBriefLessThan(String value) {
            addCriterion("dishes_brief <", value, "dishesBrief");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesBriefLessThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_brief < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesBriefLessThanOrEqualTo(String value) {
            addCriterion("dishes_brief <=", value, "dishesBrief");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDishesBriefLessThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("dishes_brief <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDishesBriefLike(String value) {
            addCriterion("dishes_brief like", value, "dishesBrief");
            return (Criteria) this;
        }

        public Criteria andDishesBriefNotLike(String value) {
            addCriterion("dishes_brief not like", value, "dishesBrief");
            return (Criteria) this;
        }

        public Criteria andDishesBriefIn(List<String> values) {
            addCriterion("dishes_brief in", values, "dishesBrief");
            return (Criteria) this;
        }

        public Criteria andDishesBriefNotIn(List<String> values) {
            addCriterion("dishes_brief not in", values, "dishesBrief");
            return (Criteria) this;
        }

        public Criteria andDishesBriefBetween(String value1, String value2) {
            addCriterion("dishes_brief between", value1, value2, "dishesBrief");
            return (Criteria) this;
        }

        public Criteria andDishesBriefNotBetween(String value1, String value2) {
            addCriterion("dishes_brief not between", value1, value2, "dishesBrief");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Byte value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDeletedEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Byte value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDeletedNotEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Byte value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDeletedGreaterThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Byte value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andDeletedLessThanOrEqualToColumn(LitemallDailyMenu.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Byte> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Byte> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Byte value1, Byte value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private LitemallDailyMenuExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        protected Criteria(LitemallDailyMenuExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public LitemallDailyMenuExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(LitemallDailyMenu.Deleted.IS_DELETED.value()) : andDeletedNotEqualTo(LitemallDailyMenu.Deleted.IS_DELETED.value());
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table litemall_daily_menu
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        void example(org.linlinjava.litemall.db.domain.LitemallDailyMenuExample example);
    }
}