package org.linlinjava.litemall.db.domain;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallDailyMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public static final Byte IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public static final Byte NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_daily_menu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_daily_menu.date
     *
     * @mbg.generated
     */
    private LocalDate date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_daily_menu.timing_id
     *
     * @mbg.generated
     */
    private Integer timingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_daily_menu.timing_name
     *
     * @mbg.generated
     */
    private String timingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_daily_menu.dishes_id
     *
     * @mbg.generated
     */
    private Integer dishesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_daily_menu.dishes_name
     *
     * @mbg.generated
     */
    private String dishesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_daily_menu.dishes_brief
     *
     * @mbg.generated
     */
    private String dishesBrief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_daily_menu.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_daily_menu.id
     *
     * @return the value of litemall_daily_menu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_daily_menu.id
     *
     * @param id the value for litemall_daily_menu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_daily_menu.date
     *
     * @return the value of litemall_daily_menu.date
     *
     * @mbg.generated
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_daily_menu.date
     *
     * @param date the value for litemall_daily_menu.date
     *
     * @mbg.generated
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_daily_menu.timing_id
     *
     * @return the value of litemall_daily_menu.timing_id
     *
     * @mbg.generated
     */
    public Integer getTimingId() {
        return timingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_daily_menu.timing_id
     *
     * @param timingId the value for litemall_daily_menu.timing_id
     *
     * @mbg.generated
     */
    public void setTimingId(Integer timingId) {
        this.timingId = timingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_daily_menu.timing_name
     *
     * @return the value of litemall_daily_menu.timing_name
     *
     * @mbg.generated
     */
    public String getTimingName() {
        return timingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_daily_menu.timing_name
     *
     * @param timingName the value for litemall_daily_menu.timing_name
     *
     * @mbg.generated
     */
    public void setTimingName(String timingName) {
        this.timingName = timingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_daily_menu.dishes_id
     *
     * @return the value of litemall_daily_menu.dishes_id
     *
     * @mbg.generated
     */
    public Integer getDishesId() {
        return dishesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_daily_menu.dishes_id
     *
     * @param dishesId the value for litemall_daily_menu.dishes_id
     *
     * @mbg.generated
     */
    public void setDishesId(Integer dishesId) {
        this.dishesId = dishesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_daily_menu.dishes_name
     *
     * @return the value of litemall_daily_menu.dishes_name
     *
     * @mbg.generated
     */
    public String getDishesName() {
        return dishesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_daily_menu.dishes_name
     *
     * @param dishesName the value for litemall_daily_menu.dishes_name
     *
     * @mbg.generated
     */
    public void setDishesName(String dishesName) {
        this.dishesName = dishesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_daily_menu.dishes_brief
     *
     * @return the value of litemall_daily_menu.dishes_brief
     *
     * @mbg.generated
     */
    public String getDishesBrief() {
        return dishesBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_daily_menu.dishes_brief
     *
     * @param dishesBrief the value for litemall_daily_menu.dishes_brief
     *
     * @mbg.generated
     */
    public void setDishesBrief(String dishesBrief) {
        this.dishesBrief = dishesBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_daily_menu.deleted
     *
     * @return the value of litemall_daily_menu.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_daily_menu.deleted
     *
     * @param deleted the value for litemall_daily_menu.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", date=").append(date);
        sb.append(", timingId=").append(timingId);
        sb.append(", timingName=").append(timingName);
        sb.append(", dishesId=").append(dishesId);
        sb.append(", dishesName=").append(dishesName);
        sb.append(", dishesBrief=").append(dishesBrief);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallDailyMenu other = (LitemallDailyMenu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()))
            && (this.getTimingId() == null ? other.getTimingId() == null : this.getTimingId().equals(other.getTimingId()))
            && (this.getTimingName() == null ? other.getTimingName() == null : this.getTimingName().equals(other.getTimingName()))
            && (this.getDishesId() == null ? other.getDishesId() == null : this.getDishesId().equals(other.getDishesId()))
            && (this.getDishesName() == null ? other.getDishesName() == null : this.getDishesName().equals(other.getDishesName()))
            && (this.getDishesBrief() == null ? other.getDishesBrief() == null : this.getDishesBrief().equals(other.getDishesBrief()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        result = prime * result + ((getTimingId() == null) ? 0 : getTimingId().hashCode());
        result = prime * result + ((getTimingName() == null) ? 0 : getTimingName().hashCode());
        result = prime * result + ((getDishesId() == null) ? 0 : getDishesId().hashCode());
        result = prime * result + ((getDishesName() == null) ? 0 : getDishesName().hashCode());
        result = prime * result + ((getDishesBrief() == null) ? 0 : getDishesBrief().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Byte("0"), "未删除"),
        IS_DELETED(new Byte("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private final Byte value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        Deleted(Byte value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Byte getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public Byte value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_daily_menu
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        date("date", "date", "DATE", true),
        timingId("timing_id", "timingId", "INTEGER", false),
        timingName("timing_name", "timingName", "VARCHAR", false),
        dishesId("dishes_id", "dishesId", "INTEGER", false),
        dishesName("dishes_name", "dishesName", "VARCHAR", false),
        dishesBrief("dishes_brief", "dishesBrief", "VARCHAR", false),
        deleted("deleted", "deleted", "TINYINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_daily_menu
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}