spring:
  profiles:
    active: db, core, admin, wx, redis #正式
#    active: dbdev, coredev, admin, wx, redisdev #开发
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

logging:
  config: classpath:logback-spring.xml

swagger:
  production: true